project:
  type: website
  render:
    - about.qmd
    - index.qmd
    - materials.qmd
    - prerequisites/*.qmd
    - day1/*.qmd
    - day1/**/*.qmd
    - methods/*.qmd


website:
  title: "AI for Coding"
  llms-txt: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Materials"
        href: materials.qmd
      - text: "Pre-requisites"
        href: prerequisites/index.qmd
      - text: "Day 1"
        href: day1/index.qmd
      - text: "Self Study"
        href: selfstudy/index.qmd
      - text: "Day 2"
        href: day2/index.qmd
      - text: "Methods"
        href: methods/index.qmd
      - text: "About"
        href: about.qmd

  sidebar:
    - title: Prerequisites
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - prerequisites/index.qmd
        - prerequisites/software.qmd
        - prerequisites/github.qmd
        - prerequisites/extensions.qmd
        - prerequisites/assistant.qmd
        - prerequisites/verify.qmd
        - prerequisites/common-problems.qmd

    - title: "Day 1"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - day1/index.qmd
        - day1/setup-overview.qmd
        - day1/ex1-1-explore-positron.qmd
        - day1/ex1-2-data-understanding.qmd

    - title: "Self Study"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - selfstudy/index.qmd

    - title: "Day 2"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - day2/index.qmd
    - title: "Methods"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - methods/index.qmd
        - methods/common-workflow.qmd
        - methods/safeguard-data.qmd
  page-navigation: true
  back-to-top-navigation: false

execute:
  freeze: true

author:
  - name: Eduard Bukin
    email: ebukin@worldbank.org
    url: https://github.com/ebukin

format:
  html:
    css: assets/custom.css
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 3
    toc-location: right
    lightbox: true
