project:
  type: website
  render:
    - about.qmd
    - index.qmd
    - prerequisites/*.qmd
    - day1/*.qmd
    - day1/**/*.qmd
    - day2/*.qmd
    - day2/**/*.qmd
    - selfstudy/*.qmd


website:
  title: "AI for Coding"
  llms-txt: true
  repo-url: https://github.com/worldbank/ai4coding
  repo-actions: [source, issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Course materials (April 2026)"
        menu:
          - text: "Day 1"
            href: day1/index.qmd
          - text: "Self Study"
            href: selfstudy/index.qmd
          - text: "Day 2"
            href: day2/index.qmd
      - text: "Setup"
        href: prerequisites/index.qmd
      - text: "Methods"
        href: methods/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/worldbank/ai4coding
        aria-label: GitHub
      - text: "Internal Resources"
        menu:
          - text: "Prosperity VP"
            href: https://worldbankgroup.sharepoint.com/sites/WBgge/
          - text: "Distributional Impact of Policies Dep."
            href: https://worldbankgroup.sharepoint.com/sites/wbpoverty
          - text: "geoPovLearn"
            href: https://worldbank.github.io/geoPovLearn/

  sidebar:
    - title: Setup
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - prerequisites/index.qmd
        - prerequisites/software.qmd
        - prerequisites/github.qmd
        - prerequisites/extensions.qmd
        - prerequisites/assistant.qmd

    - title: "Day 1"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - day1/index.qmd
        - day1/setup-overview.qmd
        - day1/ai4coding-slides-d1-1/
        - day1/ai4coding-slides-d1-2/
        - day1/ai4coding-slides-d1-3/

    - title: "Self Study"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - selfstudy/index.qmd
        - selfstudy/example-0.qmd
        - selfstudy/example-1.qmd
        - selfstudy/example-2.qmd
        - selfstudy/example-3.qmd
        - selfstudy/gmd-requirements.qmd

    - title: "Day 2"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - day2/index.qmd
    - title: "Methods"
      style: "docked"
      pinned: true
      collapse-level: 10
      contents:
        - methods/index.qmd
        - methods/common-workflow.qmd
        - methods/safeguard-data.qmd
        - methods/dime-handbook-appendix.qmd
  page-navigation: true
  back-to-top-navigation: false

execute:
  freeze: true

author:
  - name: Eduard Bukin
    email: ebukin@worldbank.org
    url: https://github.com/ebukin
    affiliations: Distributional Impact of Policies. Fiscal Policy and Growth Department

format:
  html:
    css: assets/custom.css
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 4
    toc-location: right
    lightbox: true
    code-overflow: wrap
    code-fold: show
    code-copy: true
    code-line-numbers: true
    code-block-border-left: true
